WHITE_MASK = 8
TYPE_MASK = 7

WIDTH = 8
HEIGHT = 8

DIRECTION_OFFSETS = [-WIDTH, WIDTH, -1, 1, -WIDTH - 1, -WIDTH + 1, WIDTH - 1, WIDTH + 1]

EMPTY = 0
PAWN = 1
KNIGHT = 2
BISHOP = 3
ROOK = 4
QUEEN = 5
KING = 6
PIECE_NAMES = ["  ", "P ", "K ", "B ", "R ", "Q ", "KI"]

ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
